### ISSUE TITLE
MultiRelay is not working, please help

### ISSUE THREAD

**Issue by animal463** [jselvi/MSF-MultiRelay#1]
MultiRelay is not relaying rhe hashing - blank outoput

Dear sir,

I am on Windows OS with IP 192.168.1.117 and I am running Kali Linux in Virtual with IP 192.168.1.100 on the same machine.

I have used bridged adapter for internet settings in Virtual box.

Now I have two queries
1. When I run  default responder, I can see the NTLM hashes of Windows OS but when I turned 'off' SMB and HTTP, I cannot see the hashes on Responder screen
2. When I ran Multireplay -t 192.168.1.105 -u ALL //this is another windows machine in the wireless network, I cannot Relay the hashes.

Can someone please help with the approach to successfully read and relay the hashes

**Comment by jselvi** [comment]
Hi @animal463 ,

Thanks for your message, but these scripts were written back in 2011 and are deprecated, since nowadays Metasploit has similar features built-in. Actually, these are Meterpreter Scripts, and the last time I was coding Metasploit stuff, they were all migrated into post-exploitation modules. I never did that migration because I thought the built-in capabilities of Meterpreter were good and I didn't need this anymore.

Cheers,
